spring:
  data:
    mongodb:
      database: "test"
      host:  ${MONGOHOST}
      port: ${MONGOPORT}
      password: ${MONGOPASSWORD}
      username: ${MONGOUSER}
server:
  port: 8080
paste:
  id:
    chars: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    length: 8